# -*- coding: utf-8 -*-
"""demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/matterport/Mask_RCNN/blob/master/samples/demo.ipynb

# Mask R-CNN Demo

A quick intro to using the pre-trained model to detect and segment objects.
"""

import os
import sys
import random
import math
import numpy as np
import skimage.io
from skimage.transform import rotate
import matplotlib
matplotlib.use('tkagg')
import matplotlib.pyplot as plt

# Root directory of the project
ROOT_DIR = os.path.abspath("../")
import cv2
# Import Mask RCNN
sys.path.append(ROOT_DIR)  # To find local version of the library
from mrcnn import utils
import mrcnn.model as modellib
from mrcnn import visualize
# Import COCO config
sys.path.append(os.path.join(ROOT_DIR, "samples/coco/"))  # To find local version
# import coco
from samples.coco import coco_parse_opt as coco
#%matplotlib inline
import cv2
import mrcnn.ImgPreprocess as IP
from PIL import Image
from PIL.ExifTags import TAGS, GPSTAGS
os.environ["CUDA_VISIBLE_DEVICES"] = "1"

def getExif(path):
    src_image = Image.open(path)
    info = src_image._getexif()

    # Focal Length
    focalLength = info[37386]
    focal_length = focalLength[0] / focalLength[1] # unit: mm
    focal_length = focal_length * pow(10, -3) # unit: m

    # Orientation
    orientation = info[274]

    return focal_length, orientation

def restoreOrientation(image, orientation):
    if orientation == 8:
        restored_image = rotate(image, -90)
    elif orientation == 6:
        restored_image = rotate(image, 90)
    elif orientation == 3:
        restored_image = rotate(image, 180)
    else:
        restored_image = image

    return restored_image

def rotate(image, angle):
    # https://www.pyimagesearch.com/2017/01/02/rotate-images-correctly-with-opencv-and-python/

    height = image.shape[0]
    width = image.shape[1]
    center = (width/2, height/2)

    # grab the rotation matrix (applying the negative of the
    # angle to rotate clockwise), then grab the sine and cosine
    # (i.e., the rotation components of the matrix)
    rotation_mat = cv2.getRotationMatrix2D(center, angle, 1.0)
    abs_cos = abs(rotation_mat[0, 0])
    abs_sin = abs(rotation_mat[0, 1])

    # compute the new bounding dimensions of the image
    bound_w = int(height * abs_sin + width * abs_cos)
    bound_h = int(height * abs_cos + width * abs_sin)

    # adjust the rotation matrix to take into account translation
    rotation_mat[0, 2] += bound_w / 2 - center[0]
    rotation_mat[1, 2] += bound_h / 2 - center[1]

    # perform the actual rotation and return the image
    rotated_mat = cv2.warpAffine(image, rotation_mat, (bound_w, bound_h))
    return rotated_mat

# Directory to save logs and trained model
# MODEL_DIR = "/home/user/Work/Mask_RCNN/samples/coco/logs"#os.path.join(ROOT_DIR, "logs")
# MODEL_DIR = "/home/user/Work/Mask_RCNN/weight_log/logs_5456x3632_1"#os.path.join(ROOT_DIR, "logs")
# MODEL_DIR = "/home/user/Work/Mask_RCNN/weight_log/log_5456n1024_2"#os.path.join(ROOT_DIR, "logs")

# MODEL_DIR = "/home/user/Work/Mask_RCNN/weight_log/logs_5456x3632_2/42of120/coco20191120T0221"
# MODEL_DIR = "/home/user/Work/Mask_RCNN/weight_log/logs_5456x3632_1/"
# MODEL_DIR = "/home/user/Work/Mask_RCNN/weight_log/logs_5456x3632_2/onlyhead_100"

MODEL_DIR = os.path.join(ROOT_DIR, "samples/coco/logs")
# Local path to trained weights file

print(MODEL_DIR)
# Download COCO trained weights from Releases if needed
# if not os.path.exists(COCO_MODEL_PATH):
#     utils.download_trained_weights(COCO_MODEL_PATH)

# Directory of images to run detection on
# IMAGE_DIR = os.path.join(ROOT_DIR, "images")
IMAGE_DIR = "/home/user/NAS/mingha88/LDM/"#os.path.join(ROOT_DIR, "images")
# IMAGE_DIR = "/home/user/Dataset/Jeju/3_kau_1011/Working/annotated/"#os.path.join(ROOT_DIR, "images")
# IMAGE_DIR = "/home/user/Dataset/Jeju/1_kau_1010/annotated/1024/"#os.path.join(ROOT_DIR, "images")
# IMAGE_DIR = "/home/user/Dataset/Visdrone/VisDrone2019-DET-val/images/"#os.path.join(ROOT_DIR, "images")
# IMAGE_DIR = "/home/user/PPT/"
# IMAGE_DIR = "/home/user/Dataset/Jeju/2_kau_1025/image/"#os.path.join(ROOT_DIR, "images")
# IMAGE_DIR = "/home/user/crop"#os.path.join(ROOT_DIR, "images")

"""## Configurations

We'll be using a model trained on the MS-COCO dataset. The configurations of this model are in the ```CocoConfig``` class in ```coco.py```.

For inferencing, modify the configurations a bit to fit the task. To do so, sub-class the ```CocoConfig``` class and override the attributes you need to change.
"""

class InferenceConfig(coco.CocoConfig):
    # Set batch size to 1 since we'll be running inference on
    # one image at a time. Batch size = GPU_COUNT * IMAGES_PER_GPU
    GPU_COUNT = 1
    IMAGES_PER_GPU = 1
    NUM_CLASSES = 6  # Visdrone (1+11)

config = InferenceConfig()
config.display()

"""## Create Model and Load Trained Weights"""

# Create model object in inference mode.
model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config)
# COCO_MODEL_PATH ="/home/user/Work/Mask_RCNN/weight_log/logs_5456x3632_1/mask_rcnn_coco_0160.h5"#model.find_last()
# COCO_MODEL_PATH = "/home/user/Work/Mask_RCNN/weight_log/logs_5456x3632_2/42of120/coco20191120T0221/mask_rcnn_coco_0040.h5"#model.find_last()
COCO_MODEL_PATH ="/home/user/Work/Mask_RCNN/samples/coco/logs/coco20191124T1733/mask_rcnn_coco_0194.h5" #model.find_last()
# COCO_MODEL_PATH =model.find_last() #"/home/user/Work/Mask_RCNN/samples/coco/logs/coco20191111T1858/mask_rcnn_coco_0120.h5" #model.find_last()
# Load weights trained on MS-COCO
model.load_weights(COCO_MODEL_PATH, by_name=True)

"""## Class Names

The model classifies objects and returns class IDs, which are integer value that identify each class. Some datasets assign integer values to their classes and some don't. For example, in the MS-COCO dataset, the 'person' class is 1 and 'teddy bear' is 88. The IDs are often sequential, but not always. The COCO dataset, for example, has classes associated with class IDs 70 and 72, but not 71.

To improve consistency, and to support training on data from multiple sources at the same time, our ```Dataset``` class assigns it's own sequential integer IDs to each class. For example, if you load the COCO dataset using our ```Dataset``` class, the 'person' class would get class ID = 1 (just like COCO) and the 'teddy bear' class is 78 (different from COCO). Keep that in mind when mapping class IDs to class names.

To get the list of class names, you'd load the dataset and then use the ```class_names``` property like this.
```
# Load COCO dataset
dataset = coco.CocoDataset()
dataset.load_coco(COCO_DIR, "train")
dataset.prepare()

# Print class names
print(dataset.class_names)
```

We don't want to require you to download the COCO dataset just to run this demo, so we're including the list of class names below. The index of the class name in the list represent its ID (first class is 0, second is 1, third is 2, ...etc.)
"""

# COCO Class names
# Index of the class in the list is its ID. For example, to get ID of
# the teddy bear class, use: class_names.index('teddy bear')

class_names = ["BG","Trash","Car","Building","Ocean","Land"]
result = {'rois':0, 'masks':1, 'class_ids':2, 'scores':3}
# class_names = ['BG','pedestrian','people','bicycle','car','van','truck', 'tricycle','awning-tricycle','bus','motor','others']
"""## Run Object Detection"""
idx = 0
# filenames = os.listdir(IMAGE_DIR)
filenames = os.listdir(IMAGE_DIR)
idx = 0
# Load a random image from the images folder
for file_names in filenames:
    if ".jpg" in file_names.lower():
        # print(file_names)
        # next(os.walk(IMAGE_DIR))[2]
        # image = skimage.io.imread(os.path.join(IMAGE_DIR, random.choice(file_names)))
        # img_cv = cv2.imread(os.path.join(IMAGE_DIR,file_names[i]))
        image = cv2.imread(os.path.join(IMAGE_DIR,file_names))
        orientation = IP.getExif(IMAGE_DIR+file_names)
        # if orientation is not None:
        image = IP.restoreOrientation(image,orientation)
        image = image[:,:,::-1]

        # Run detection
        results = model.detect([image],verbose=1)

        # Visualize results
        ob_idx = 0
        target_rois=[]
        target_masks=[]
        target_class_ids=[]
        target_scores=[]
        flag = 0
        r = results[0]
        print("file name, detected!!",file_names,len(r['class_ids']))
        test = 1
        # for object_id in r['class_ids']:
        #     if object_id == 1 or object_id == 2 or object_id == 3 : # ocean land   np.concatenate((np.array([[1,2,3]]),np.array([[4,5,6]])))
        #         if flag == 0:
        #             target_rois = np.array([r['rois'][ob_idx]])
        #             target_masks = np.array([r['masks'][ob_idx]])
        #             target_class_ids = np.array([r['class_ids'][ob_idx]])
        #             target_scores = np.array([r['scores'][ob_idx]])
        #             flag = 1
        #         else:
        #             target_rois = np.concatenate((target_rois,np.array([r['rois'][ob_idx]])))
        #             target_masks = np.concatenate((target_masks,np.array([r['masks'][ob_idx]])))
        #             target_class_ids = np.concatenate((target_class_ids,np.array([r['class_ids'][ob_idx]])))
        #             target_scores = np.concatenate((target_scores,np.array([r['scores'][ob_idx]])))
        #
        #     ob_idx += 1
        #
        # visualize.display_instances(idx, image, target_rois, target_masks, target_class_ids, class_names,
        #                             target_scores)  # np.delete(r['rois'],(1),axis=0) (1):row idx, axis=0
        #visualize.display_instances(file_names, image, r['rois'], r['masks'], r['class_ids'], class_names, r['scores']) #np.delete(r['rois'],(1),axis=0) (1):row idx, axis=0


        idx +=1

    else: continue



test = 1


